const TOP_MOVIES = [
	'Top Gun',
	'Scent of a Woman',
	'Love & Other Drugs',
	'The Godfather',
	'Saturday Night Fever',
	'Jerry Maguire',
	'Rocky',
	'Rocky II',
	'Rocky III',
	'Rocky IV',
	'Terminator 2: Judgment Day',
	'Jobs',
	'No Strings Attached',
	'Fast Five',
	'Blood Diamond',
	'Gladiator',
	'Troy',
	'Casino Royale',
	'Heat',
	'Casino',
	'A Bronx Tale',
	'Scarface',
	'The Devil’s Advocate',
	'Ocean’s Eleven',
	'The Last Samurai',
	'Days of Thunder',
	'Fight Club',
	'Inglourious Basterds',
	'The Curious Case of Benjamin Button',
	'Django Unchained',
	'Body of Lies',
	'Eagle Eye',
	'Gangs of New York',
	'Unfaithful',
	'The Wolf of Wall Street',
	'Step Up',
	'Bruce Almighty',
	'Forrest Gump',
	'Captain Phillips',
	'The Great Wall',
	'Shooter',
	'The Expendables',
	'Coach Carter',
	'xXx',
	'The Dark Knight',
	'The Dark Knight Rises',
	'The Fighter',
	'Exodus: Gods and Kings',
	'The Pursuit of Happyness',
	'Men in Black',
	'I, Robot',
	'Hancock',
	'Independence Day',
	'The Karate Kid',
	'Unstoppable',
	'Man of Steel',
	'The Mummy',
	'Gridiron Gang',
	'10 Things I Hate About You',
	'21',
	'X-Men: The Last Stand',
	'Real Steel',
	'Van Helsing',
	'Rush',
	'Ted',
	'Transformers',
	'Transformers: Revenge of the Fallen',
	'Wanted',
	'Ghost Rider',
	'Gone in 60 Seconds',
	'Drive Angry',
	'Never Back Down',
	'My Boss’s Daughter',
	'Beowulf',
	'Predator',
	'End of Days',
	'Death Race',
	'A Time to Kill'
];

export default TOP_MOVIES;
